# Generated by Django 3.1.2 on 2020-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
